### ISSUE TITLE
The requested URL /@gulp-sourcemaps/map-sources was not found on this server

### ISSUE THREAD

**Issue by kroney** [gulp-sourcemaps/gulp-sourcemaps#292]
Hey
since this morning we're getting the following error when trying to install:
The requested URL /@gulp-sourcemaps/map-sources was not found on this server
I'm guessing this has something to do with the new release

**Comment by boxcee** [comment]
Version lock to `"gulp-sourcemaps": "1.11.1"` works as a temporary fix.

**Comment by JE-DW** [comment]
For those who want to stay in 2.x.x, the latest version working is `"gulp-sourcemaps": "2.4.1"`. So it's just a problem with `2.5.0`.

**Comment by floridoo** [comment]
Scoped packages need a version of npm greater than 2.7.0, could this be your problem?

**Comment by qrpike** [comment]
This broke our builds since we use a NPM caching server which seems not to support scoping.

**Comment by nmccready** [comment]
Please use stricter versioning on your production builds. Lastly, use npm shrinkwrap or yarn for lock files. In the end you guys need to use a newer version of npm, or yarn. 

@phated any other thoughts?

I wonder if the 1.X version should not be using scoped packages and something else.

**Comment by jberrydev** [comment]
@floridoo  So I am on npm version 3.3.12 and this still breaks.

**Comment by phated** [comment]
No. People should be using updated npm clients and better proxies. This feature has been out for almost 2 years.

**Comment by JE-DW** [comment]
From @floridoo : 
> Scoped packages need a version of npm greater than 2.7.0, could this be your problem?

I was running on npm `3.10.8`.

**Comment by phated** [comment]
You likely have a proxy that doesn't support scoped packages. Fix your environment.

**Comment by JE-DW** [comment]
Thanks, I just find out we are using sinopia. So yeah, we plan to change that.

**Comment by anjunatl** [comment]
@phated I'm having the same issue with **node v6.9.2 / npm v3.10.9.** I see your comments about proxies/scoped packages but I don't understand what that's in reference to - I believe my org uses an internal artifactory mirror, so is this the documentation I should be forwarding to the folks maintaining that? https://www.jfrog.com/confluence/display/RTF/Npm+Registry#NpmRegistry-NpmScopePackages

_"Artifactory fully supports npm scope packages. The support is transparent to the user and does not require any different usage of the npm client. (...) If Artifactory is running behind a reverse proxy, make sure to disable URL decoding on the proxy itself in order to work with npm scope packages."_

Thanks!

**Comment by jberrydev** [comment]
@phated you may want to document your change as this is a breaking change without proper server configuration in some instances.

**Comment by phated** [comment]
As far as I'm concerned, semver only considers the API of the module itself. Not your environment nor installers you choose to use outside of common conventions.

**Comment by phated** [comment]
@anjunatl it's right at the top of the docs you linked....
> Npm 'slash' character encoding
By default, the npm client encodes slash characters ('/') to their ASCII representation ("%2f") before communicating with the npm registry. If you are running Tomcat as your HTTP container (the default for Artifactory), this generates an "HTTP 400" error since Tomcat does not allow encoded slashes by default. In order work with npm scoped packages, you can override this default behavior by defining the following property in the catalina.properties file of your Tomcat:
org.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
Note that since Artifactory version 4.4.3, the bundled Tomcat is configured by default to enable encoded slashes. If you are using a previous version you will need to adjust the Tomcat property above.

**Comment by jberrydev** [comment]
@phated basically anyone using your latest of 1.x that doesn't setup there environment to handle scoped packages is hosed. I would call that breaking.  I am with @nmccready that the 1.12.0 should not contain this change.  Scoped packages are a feature that not all have the option to support and normally should be used for internal dev projects. I would assume if I were developing something that was going to be public facing, I would make sure I had a major version that would not require my consumers to update server configurations.  That is just me. Other users that see this for now if you cannot support scoped packages just use hard versions <=1.11.0 or <=2.4.1 and if you can support scoped packages update your server configurations as needed.

**Comment by phated** [comment]
@jberrydev sorry you feel that way.  Obviously our priorities are at odds and I don't plan to support your non-standard workflow.  You can pin the dependency for non-standard workflows or upgrade your environment to be >2 years out-of-date.  I'm going to be locking this thread.

**Comment by phated** [comment]
If you are using `sinopia`, you probably want to switch to https://github.com/verdaccio/verdaccio
