### ISSUE TITLE
[CSS] Need new CSS processor: Sourcemaps for imported files are not correct

### ISSUE THREAD

**Issue by mikemaccana** [gulp-sourcemaps/gulp-sourcemaps#349]
Similar to #271, except the source maps are generated, but not pointing at the relevant resulting file.

I have `scss/_colors.scss`, which is `@import`ed by `scss/style.scss`.

`scss/style.scss` is compiled to build `css/style.css`. 

However the mapping for `scss/_colors.scss` points to a non-existent, unused file called `css/_colors.css`

See the image below.

![image](https://user-images.githubusercontent.com/172594/38925599-03c454aa-42f8-11e8-92a9-3b168c1aeb67.png)

I'm not 100% sure what the source map for an `@import`ed file should be, but the current mapping to a non-existent file doesn't seem correct.

**Comment by nmccready** [comment]
From what I remember the problem boils down to bug in the parser css library. See: #351 as we are considering alternative libraries.

**Comment by nmccready** [comment]
I am going to try and bang this out today as part of Hacktober.

**Comment by nmccready** [comment]
So this branch https://github.com/gulp-sourcemaps/gulp-sourcemaps/tree/bug/nmccready/cssSourceMapping might not get merged in as gulp-sourcemaps has been rolled into gulp core (4.X). So there is not much reason to continue gulp-sourcemaps .

I could be convinced otherwise to at least fix this issue for gulp 3.X but I would prefer the solution is identical or close to the same from core to here. The real fix itself will be in https://github.com/gulp-sourcemaps/identity-map as js and css generation is being removed from `init`.

**Comment by ray007** [comment]
I'm having the same problem with creating a sourcemap with `gulp-cleancss`, when I have one source file that is importing 4 other files.

Checking with `sourcemaps.mapSources()`, it's called 5 times, every time with the filename of the root css file.

**Comment by phated** [comment]
If you need this change, you can install [`@gulp-sourcemaps/identity-map`](https://www.npmjs.com/package/@gulp-sourcemaps/identity-map) and use it within your pipeline.  I just released v2.0.0 which swaps the `css` library with `postcss` to generate CSS sourcemaps.  We won't be able to bump it in gulp-sourcemaps because it required a bunch of breaking changes.
